version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
volumes:
  mongo_data:
